openapi: 3.1.0
info:
  title: Task Management API
  description: |
    REST API for managing tasks with user-based data isolation.

    This API provides CRUD operations for task management. All endpoints
    require a user_id path parameter for data isolation. In future phases,
    user_id will be extracted from JWT tokens instead of path parameters.

    **Key Features:**
    - Create, read, update, and delete tasks
    - User-based data isolation (tasks scoped to user_id)
    - Automatic timestamp management
    - Task completion toggle endpoint
    - Interactive API documentation (Swagger UI)
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server (future)

tags:
  - name: tasks
    description: Task management operations

paths:
  /api/{user_id}/tasks:
    get:
      tags:
        - tasks
      summary: List all tasks for a user
      description: |
        Retrieves all tasks belonging to the specified user.
        Tasks are returned in descending order by creation date (newest first).
      operationId: listTasks
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        '200':
          description: Successfully retrieved task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                emptyList:
                  summary: Empty task list
                  value: []
                taskList:
                  summary: List with tasks
                  value:
                    - id: "550e8400-e29b-41d4-a716-446655440000"
                      user_id: "user123"
                      title: "Complete project documentation"
                      description: "Write API docs and setup guide"
                      completed: false
                      created_at: "2026-02-06T10:30:00Z"
                      updated_at: "2026-02-06T10:30:00Z"
                    - id: "660e8400-e29b-41d4-a716-446655440001"
                      user_id: "user123"
                      title: "Review pull request"
                      description: null
                      completed: true
                      created_at: "2026-02-05T14:20:00Z"
                      updated_at: "2026-02-06T09:15:00Z"
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      tags:
        - tasks
      summary: Create a new task
      description: |
        Creates a new task for the specified user.
        The task ID and timestamps are automatically generated.
      operationId: createTask
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            examples:
              withDescription:
                summary: Task with description
                value:
                  title: "Complete project documentation"
                  description: "Write comprehensive API docs"
              withoutDescription:
                summary: Task without description
                value:
                  title: "Review pull request"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "user123"
                title: "Complete project documentation"
                description: "Write comprehensive API docs"
                completed: false
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T10:30:00Z"
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/{user_id}/tasks/{task_id}:
    get:
      tags:
        - tasks
      summary: Get a single task
      description: |
        Retrieves a specific task by ID.
        Returns 404 if the task doesn't exist or belongs to a different user.
      operationId: getTask
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
        - $ref: '#/components/parameters/TaskIdParam'
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "user123"
                title: "Complete project documentation"
                description: "Write comprehensive API docs"
                completed: false
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T10:30:00Z"
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      tags:
        - tasks
      summary: Update a task
      description: |
        Updates an existing task. All fields in the request body are optional.
        Only provided fields will be updated. The updated_at timestamp is
        automatically refreshed.
      operationId: updateTask
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
        - $ref: '#/components/parameters/TaskIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            examples:
              updateTitle:
                summary: Update title only
                value:
                  title: "Updated task title"
              updateAll:
                summary: Update all fields
                value:
                  title: "Updated task title"
                  description: "Updated description"
                  completed: true
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "user123"
                title: "Updated task title"
                description: "Updated description"
                completed: true
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T11:45:00Z"
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - tasks
      summary: Delete a task
      description: |
        Permanently deletes a task. This operation cannot be undone.
        Returns 404 if the task doesn't exist or belongs to a different user.
      operationId: deleteTask
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
        - $ref: '#/components/parameters/TaskIdParam'
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Task deleted successfully"
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      tags:
        - tasks
      summary: Toggle task completion status
      description: |
        Toggles the completion status of a task.
        If the task is incomplete, it will be marked as completed.
        If the task is completed, it will be marked as incomplete.
        The updated_at timestamp is automatically refreshed.
      operationId: toggleTaskCompletion
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
        - $ref: '#/components/parameters/TaskIdParam'
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "user123"
                title: "Complete project documentation"
                description: "Write comprehensive API docs"
                completed: true
                created_at: "2026-02-06T10:30:00Z"
                updated_at: "2026-02-06T12:00:00Z"
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    UserIdParam:
      name: user_id
      in: path
      required: true
      description: |
        User identifier. In future phases, this will be extracted from JWT tokens
        instead of being passed as a path parameter.
      schema:
        type: string
        example: "user123"

    TaskIdParam:
      name: task_id
      in: path
      required: true
      description: Unique task identifier (UUID)
      schema:
        type: string
        format: uuid
        example: "550e8400-e29b-41d4-a716-446655440000"

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        user_id:
          type: string
          description: Owner of the task
          example: "user123"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title/summary
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Detailed task description
          example: "Write comprehensive API documentation including setup instructions"
        completed:
          type: boolean
          description: Task completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created (UTC)
          example: "2026-02-06T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last modified (UTC)
          example: "2026-02-06T10:30:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title/summary (required, cannot be empty)
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Detailed task description (optional)
          example: "Write comprehensive API documentation"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title (optional)
          example: "Updated task title"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Updated task description (optional)
          example: "Updated description"
        completed:
          type: boolean
          description: Updated completion status (optional)
          example: true

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the validation error
              msg:
                type: string
                description: Error message
              type:
                type: string
                description: Error type
          example:
            - loc: ["body", "title"]
              msg: "field required"
              type: "value_error.missing"

  responses:
    NotFound:
      description: Task not found or belongs to a different user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"

    ValidationError:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "ensure this value has at most 200 characters"
                type: "value_error.any_str.max_length"

    InternalServerError:
      description: Unexpected server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Internal server error"
